name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Prepare Dockerfile
        run: cp ./docker/Dockerfile.user ./Dockerfile

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: pankajkumardev/flowpay:${{ github.ref_name }} # Tag using Git branch name or tag

      - name: Verify Pushed Image
        run: docker pull pankajkumardev/flowpay:${{ github.ref_name }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull pankajkumardev/flowpay:${{ github.ref_name }}  # Pull image using the versioned tag
            sudo docker stop web-app || true
            sudo docker rm web-app || true
            sudo docker run -e DATABASE_URL=${{secrets.DB_URL}} -e JWT_SECRET=${{secrets.JWT_SECRET}} -e NEXTAUTH_URL=http://ec2-44-202-164-212.compute-1.amazonaws.com:3005 -d --name web-app -p 3005:3000 pankajkumardev/flowpay:${{ github.ref_name }}  # Run the container with the specific tag

      # Cleanup Docker images and containers
      - name: Cleanup Docker images and containers
        run: |
          echo "Cleaning up Docker resources"
          # Remove unused Docker images and containers to free up space
          sudo docker system prune -a -f --volumes
          sudo docker builder prune -a -f
          sudo docker container prune -f
          sudo docker image prune -a -f
